inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.0
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/**/*
    - db/migrate/*
    - features/support/action_view.rb
    - vendor/**/*

Metrics/LineLength:
  Max: 100
  Exclude:
    - config/environments/**/*
    - config/initializers/**/*
    - db/seeds.rb
    - lib/tasks/cucumber.rake
    - features/support/env.rb
    - script/cucumber
    - 'app/models/methodologies.rb'
    - 'app/models/recording_methods.rb'
    - 'app/models/shared_with.rb'

Metrics/BlockLength:
  Max: 35
  Exclude:
    - spec/**/*
    - features/step_definitions/**/*
    - lib/tasks/**/*

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 200

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FileName:
  Exclude:
    - 'Dangerfile'

Style/SignalException:
  Exclude:
    - 'Dangerfile'

Lint/UnreachableCode:
  Exclude:
    - 'Dangerfile'

Style/DoubleNegation:
  Enabled: false
