inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4.1
  Include:
    - Gemfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 100
  Exclude:
    - config/environments/**/*
    - config/initializers/**/*
    - db/seeds.rb
    - lib/tasks/cucumber.rake
    - features/support/env.rb
    - script/cucumber

Metrics/BlockLength:
  Max: 35
  Exclude:
    - spec/**/*
    - features/step_definitions/**/*
    - lib/tasks/**/*

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 200

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FileName:
  Exclude:
    - 'Dangerfile'

Style/SignalException:
  Exclude:
    - 'Dangerfile'

Lint/UnreachableCode:
  Exclude:
    - 'Dangerfile'

Style/PredicateName:
  Exclude:
    - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false
