options:
  formatter: stylish
  merge-default-rules: true
files:
  include: 'app/assets/stylesheets/**/*.s+(a|c)ss'
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  force-element-nesting:
    - 0
  force-pseudo-nesting:
    - 0
  property-sort-order:
    - 0
  mixins-before-declarations:
    - 0
  hex-length:
    - 0
  no-color-literals:
    - 0
  no-vendor-prefixes:
    - 0
  nesting-depth:
    - max-depth: 3
  quotes:
    - 1
    - style: double
  indentation:
    - 0
  leading-zero:
    - 0
  shorthand-values:
    - 1
    - allowed-shorthands:
      - 1
      - 2
